name: ChiliLinux Update Key

# Controls when the workflow will run
on:
  schedule:
    #18:00 no UTC-4 (22:00 UTC) todas as sextas-feiras:
    - cron: "0 22 * * 5"  # Minuto 0, Hora 22 (UTC), Qualquer dia do mês, Qualquer mês, Sexta-feira (5)
  push:
    #branches: [ "master", "main", "*" ]
    branches: ["*"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This gives the GITHUB_TOKEN permission to push
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Enable debug logging
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        run: echo "Debugging is enabled"

      - id: install-build-dependencies
        shell: bash
        run: |
          {
          sudo apt-get autoremove -y
          sudo apt-get update -y
          sudo apt-get install -y -qq \
          build-essential \
          cmake \
          git \
          libarchive-dev \
          libarchive-tools \
          libcurl4-openssl-dev \
          libgpgme-dev \
          libssl-dev \
          zip \
          python3-pip \
          tmate \
          inetutils-tools
          sudo pip3 install meson
          sudo pip3 install ninja
          } > /dev/null 2>&1

      # Iniciar a sessão tmate e exibir o link de conexão
      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'

      - name: Display the current user in host
        run: |
          # Display the current user in host
          echo "#########################################"
          echo "Current host is: $(hostname)"
          echo "Current user is: $(whoami)"
          echo "Current user ID is: $(id -u)"
          echo "Current user details:"
          id
          echo "#########################################"
          df -hT
          echo "#########################################"
          ls -lah --color=auto /mnt
          echo "#########################################"

      - name: install pacman
        shell: bash
        env:
          #PACMAN_VERSION: 6.0.1
          PACMAN_VERSION: 6.0.2
        run: |
          {
          sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
          pushd pacman
          sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
          sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
          pushd pacman-${PACMAN_VERSION}
          #sudo patch -p1 -i ../pacman-sync-first-option.patch
          sudo meson --prefix=/usr \
                      --buildtype=plain \
                      -Ddoc=disabled \
                      -Ddoxygen=enabled \
                      -Dscriptlet-shell=/usr/bin/bash \
                      -Dldconfig=/usr/bin/ldconfig \
                      build
          sudo meson compile -C build
          sudo meson install -C build
          popd
          sudo install -m644 pacman.conf /etc/pacman.conf
          sudo sed -i '/^DownloadUser/s/^/#/' /etc/pacman.conf
          sudo install -m644 makepkg.conf /etc/
          sudo mkdir -p /etc/pacman.d
          sudo touch /etc/pacman.d/mirrorlist
          popd
          sudo rm -rf pacman
          } > /dev/null 2>&1

          #add chili repository
          {
          sudo sed -i '/\[core\]/{h;s/.*/\[chili-update-stable\]/;p;x;}' /etc/pacman.conf
          sudo sed -i '/\[core\]/{h;s/.*/SigLevel = PackageRequired/;p;x;}' /etc/pacman.conf
          sudo sed -i '/\[core\]/{h;s/.*/Server = https:\/\/repo.chililinux.com\/update-stable\/$arch/;p;x;}' /etc/pacman.conf
          sudo sed -i '/\[core\]/{h;s/.*//;p;x;}' /etc/pacman.conf
          echo '
          [chili-testing]
          SigLevel = PackageRequired
          Server = https://repo.chililinux.com/testing/$arch' | sudo tee -a /etc/pacman.conf
          echo '
          [chili-stable]
          SigLevel = PackageRequired
          Server = https://repo.chililinux.com/stable/$arch' | sudo tee -a /etc/pacman.conf
          } > /dev/null 2>&1

      - name: install keyrings
        shell: bash
        run: |
          {
          sudo install -dm755 /usr/share/pacman/keyrings/
          sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/manjaro-keyring.git
          pushd manjaro-keyring
            sudo install -m0644 manjaro.gpg     /usr/share/pacman/keyrings/
            sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
          popd
          sudo rm -rf manjaro-keyring

          mkdir -p archlinux-keyring
          pushd archlinux-keyring
            wget https://archlinux.org/packages/core/any/archlinux-keyring/download -O /tmp/archlinux-keyring.tar.zst
            tar --use-compress-program=unzstd --strip-components=4 --wildcards -xvf /tmp/archlinux-keyring.tar.zst usr/share/pacman/keyrings/*
            sudo install -m0644 archlinux.gpg     /usr/share/pacman/keyrings/
            sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
          popd
          sudo rm -rf archlinux-keyring

          sudo git clone --depth 1 https://github.com/chililinux/chili-keyring.git
          pushd chili-keyring
            sudo install -m0644 chili.gpg     /usr/share/pacman/keyrings/
            sudo install -m0644 chili-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 chili-revoked /usr/share/pacman/keyrings/
          popd
          sudo rm -rf chili-keyring

          sudo git clone --depth 1 https://github.com/biglinux/biglinux-keyring.git
          pushd biglinux-keyring
            sudo install -m0644 biglinux.gpg     /usr/share/pacman/keyrings/
            sudo install -m0644 biglinux-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 biglinux-revoked /usr/share/pacman/keyrings/
          popd
          sudo rm -rf biglinux-keyring

          sudo git clone --depth 1 https://github.com/communitybig/community-keyring.git
          pushd community-keyring
            sudo install -m0644 community.gpg     /usr/share/pacman/keyrings/
            sudo install -m0644 community-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 community-revoked /usr/share/pacman/keyrings/
          popd
          sudo rm -rf community-keyring
          } > /dev/null 2>&1

      - name: Update Key
        run: |
          {
          sudo pacman-key --init
          sudo pacman-key --populate archlinux manjaro chili biglinux community
          cp -fa /etc/pacman.d/gnupg/pubring.gpg  usr/share/pacman/keyrings/
          cp -fa /etc/pacman.d/gnupg/trustdb.gpg  usr/share/pacman/keyrings/
          } > /dev/null 2>&1

      - name: Update github
        run: |
          {
          # https://api.github.com/users/username
          git add --all
          git config --local user.email "133667052+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "github-actions bot Update $(date +%Y-%m-%d)"
          } > /dev/null 2>&1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          branch: ${{ github.ref }}

      - name: Send Hooks ChiliLinux Build Package
        shell: bash
        run: |
          repo_name=${{ github.repository }}
          IFS='/' read -r owner repo <<< "$repo_name"
          # Define a variável data
          data="{\
            \"event_type\": \"$repo\", \
            \"client_payload\": { \
            \"branch\": \"${{ github.ref_name }}\", \
            \"branch_type\": \"stable\", \
            \"url\": \"https://github.com/${{ github.repository }}\" \
            }\
          }"

          # Executa o comando curl com a variável data
          response=$(curl -s -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.REPOSITORY_TOKEN }}" \
            --data "$data" \
            -w "%{http_code}" \
            -o /dev/null \
            "https://api.github.com/repos/chililinux/build-package/dispatches")

          echo "Response: $response"
          if [[ "$response" != "204" ]]; then
            echo "$response: Falha ao acionar o workflow de build '${{ github.repository }}'"
            exit 1
          else
            echo "$response: Workflow de build '${{ github.repository }}' acionado com sucesso."
          fi
